
import __ASTRO_IMAGE_IMPORT_o89Wz from "../../assets/blog-placeholder-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffirst-post.md";
import __ASTRO_IMAGE_IMPORT_Z1PVYzz from "../../assets/blog-placeholder-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthird-post.md";
import __ASTRO_IMAGE_IMPORT_Z1Yq4sn from "../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown-style-guide.md";
import __ASTRO_IMAGE_IMPORT_Z1F4X4R from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown-style-guide.md";
import __ASTRO_IMAGE_IMPORT_1inyCS from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsecond-post.md";
import __ASTRO_IMAGE_IMPORT_ZWVqE from "2025/ZZ_Celia.png?astroContentImageFlag=&importer=src%2Fcontent%2Fstormlight%2Fjuly_17_2025.md";
import __ASTRO_IMAGE_IMPORT_1o9Vqf from "2025/MandelbrotEquation.png?astroContentImageFlag=&importer=src%2Fcontent%2Fstormlight%2Fjuly_17_2025.md";
import __ASTRO_IMAGE_IMPORT_16jJa0 from "2025/IlluminationDummy.png?astroContentImageFlag=&importer=src%2Fcontent%2Fstormlight%2Fjuly_17_2025.md";
import __ASTRO_IMAGE_IMPORT_ZT9lmL from "../../assets/StormlightPlaceholder.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fstormlight%2Fjuly_17_2025.md";
import __ASTRO_IMAGE_IMPORT_ZeKX7b from "Raybenez.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md";
import __ASTRO_IMAGE_IMPORT_Z2lPEqi from "Barceline.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md";
import __ASTRO_IMAGE_IMPORT_Z1lR9jc from "Marceline.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md";
import __ASTRO_IMAGE_IMPORT_Ze2aoV from "BarcelineBack.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md";
import __ASTRO_IMAGE_IMPORT_47PRt from "HadesGuitar.PNG?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md";
import __ASTRO_IMAGE_IMPORT_Z2g2bXl from "PokemonTwins.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md";
import __ASTRO_IMAGE_IMPORT_Z1Wm8PX from "Exeggutor.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md";
export default new Map([["../../assets/blog-placeholder-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffirst-post.md", __ASTRO_IMAGE_IMPORT_o89Wz], ["../../assets/blog-placeholder-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthird-post.md", __ASTRO_IMAGE_IMPORT_Z1PVYzz], ["../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown-style-guide.md", __ASTRO_IMAGE_IMPORT_Z1Yq4sn], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown-style-guide.md", __ASTRO_IMAGE_IMPORT_Z1F4X4R], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsecond-post.md", __ASTRO_IMAGE_IMPORT_1inyCS], ["2025/ZZ_Celia.png?astroContentImageFlag=&importer=src%2Fcontent%2Fstormlight%2Fjuly_17_2025.md", __ASTRO_IMAGE_IMPORT_ZWVqE], ["2025/MandelbrotEquation.png?astroContentImageFlag=&importer=src%2Fcontent%2Fstormlight%2Fjuly_17_2025.md", __ASTRO_IMAGE_IMPORT_1o9Vqf], ["2025/IlluminationDummy.png?astroContentImageFlag=&importer=src%2Fcontent%2Fstormlight%2Fjuly_17_2025.md", __ASTRO_IMAGE_IMPORT_16jJa0], ["../../assets/StormlightPlaceholder.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fstormlight%2Fjuly_17_2025.md", __ASTRO_IMAGE_IMPORT_ZT9lmL], ["Raybenez.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md", __ASTRO_IMAGE_IMPORT_ZeKX7b], ["Barceline.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md", __ASTRO_IMAGE_IMPORT_Z2lPEqi], ["Marceline.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md", __ASTRO_IMAGE_IMPORT_Z1lR9jc], ["BarcelineBack.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md", __ASTRO_IMAGE_IMPORT_Ze2aoV], ["HadesGuitar.PNG?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md", __ASTRO_IMAGE_IMPORT_47PRt], ["PokemonTwins.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md", __ASTRO_IMAGE_IMPORT_Z2g2bXl], ["Exeggutor.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2FGuitars.md", __ASTRO_IMAGE_IMPORT_Z1Wm8PX]]);
		